"""Initial schema

Revision ID: 9870c3699254
Revises: 
Create Date: 2026-08-17 20:11:33.692984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9870c3699254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localizacoes_usuarios')
    with op.batch_alter_table('campanhas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_campanhas_nome'))

    op.drop_table('campanhas')
    op.drop_table('imagens_excluidas')
    op.drop_table('tarefas')
    with op.batch_alter_table('campanhas_imagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_campanhas_imagens_apagada'))
        batch_op.drop_index(batch_op.f('idx_campanhas_imagens_campanha'))

    op.drop_table('campanhas_imagens')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('senha',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('campanhas_imagens',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('campanha_id', sa.INTEGER(), nullable=False),
    sa.Column('imagem_path', sa.TEXT(), nullable=False),
    sa.Column('apagada', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('fileid', sa.TEXT(), nullable=True),
    sa.Column('folderid', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanhas_imagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_campanhas_imagens_campanha'), ['campanha_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_campanhas_imagens_apagada'), ['apagada'], unique=False)

    op.create_table('tarefas',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('motivo', sa.TEXT(), nullable=True),
    sa.Column('estabelecimento', sa.TEXT(), nullable=True),
    sa.Column('localidade', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('data_inicio', sa.TEXT(), nullable=True),
    sa.Column('data_fim', sa.TEXT(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens_excluidas',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('cod', sa.TEXT(), nullable=False),
    sa.Column('campanha', sa.TEXT(), nullable=False),
    sa.Column('imagem_path', sa.TEXT(), nullable=False),
    sa.Column('excluido_por', sa.TEXT(), nullable=False),
    sa.Column('data_exclusao', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campanhas',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('cod', sa.TEXT(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('data_criacao', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanhas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_campanhas_nome'), ['nome'], unique=False)

    op.create_table('localizacoes_usuarios',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('latitude', sa.REAL(), nullable=False),
    sa.Column('longitude', sa.REAL(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
